package GUI;

import autres.Caisse_Properties;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class PropertiesDialog extends JDialog {
    private Caisse_Properties caisseProperties;
    private JLabel nomMagasinLabel;
    private JLabel adresseMagasinLabel;
    private JTextField nomMagasinField;
    private JTextField adresseMagasinField;
    private JButton okButton;
    private JButton cancelButton;

    public PropertiesDialog() {
        super((Frame) null, "Gestion des Propriétés", true);
        caisseProperties = new Caisse_Properties();
        caisseProperties.chargerProprietes();

        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(2, 2, 10, 10));

        nomMagasinLabel = new JLabel("Nom du Magasin:");
        adresseMagasinLabel = new JLabel("Adresse du Magasin:");
        nomMagasinField = new JTextField(caisseProperties.getNomMagasin());
        adresseMagasinField = new JTextField(caisseProperties.getAdresseMagasin());

        panel.add(nomMagasinLabel);
        panel.add(nomMagasinField);
        panel.add(adresseMagasinLabel);
        panel.add(adresseMagasinField);

        okButton = new JButton("OK");
        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String nomMagasin = nomMagasinField.getText();
                String adresseMagasin = adresseMagasinField.getText();

                caisseProperties.setNomMagasin(nomMagasin);
                caisseProperties.setAdresseMagasin(adresseMagasin);

                dispose();
            }
        });

        cancelButton = new JButton("Annuler");
        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        JPanel buttonPanel = new JPanel();
        buttonPanel.add(okButton);
        buttonPanel.add(cancelButton);

        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(panel, BorderLayout.CENTER);
        getContentPane().add(buttonPanel, BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
